name: Generate ER Diagram

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sdRDM library
      uses: JR-1991/generate-sdrdm-api@v3.1
      with:
        library_name: "FAIRFlow"
        schema_path: "./specifications/datamodel.md"
