name: Generate ER Diagram

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sdRDM library
      uses: JR-1991/generate-sdrdm-api@v3
      with:
        library_name: "FAIRFlowChemistry"
        schema_path: "./specifications/datamodel_b07_tc.md"
        schema: "true"
        branch: "main"
